# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-05-13T16:56:36+00:00

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, Field, RootModel


class User(BaseModel):
    admin: bool = Field(..., description="Whether user is an admin")
    balance: int = Field(..., description="User's STK balance")
    banned: bool = Field(..., description="Whether user is banned")
    id: int | None = Field(None, description="User ID")
    inserted_at: datetime | None = Field(None, description="Creation timestamp")
    updated_at: datetime | None = Field(None, description="Update timestamp")
    username: str = Field(..., description="Username")


class From(BaseModel):
    id: int | None = Field(None, description="From user ID")
    username: str | None = Field(None, description="From username")


class To(BaseModel):
    id: int | None = Field(None, description="To user ID")
    username: str | None = Field(None, description="To username")


class TransactionResponse(BaseModel):
    amount: int = Field(..., description="Transaction amount")
    from_: From = Field(..., alias="from")
    id: int = Field(..., description="Transaction ID")
    label: str | None = Field(None, description="Transaction label")
    time: datetime = Field(..., description="Transaction timestamp")
    to: To


class RequestDeniedData(BaseModel):
    denied_by_id: int = Field(..., description="User ID that denied the request")
    request_id: int = Field(..., description="Request ID")
    status: str = Field(..., description="New request status")


class Transaction(BaseModel):
    amount: int = Field(..., description="Transaction amount")
    from_: From = Field(..., alias="from")
    id: int = Field(..., description="Transaction ID")
    label: str | None = Field(None, description="Transaction label")
    time: datetime = Field(..., description="Transaction timestamp")
    to: To


class TransferCompletedData(BaseModel):
    amount: int = Field(..., description="Amount transferred")
    from_id: int = Field(..., description="Sender user ID")
    role: str = Field(..., description="Role of the event recipient (sender or receiver)")
    to_id: int = Field(..., description="Recipient user ID")
    transaction_id: int = Field(..., description="Transaction ID")


class Type(StrEnum):
    transfer_completed = "transfer.completed"


class TransferCompletedEvent(BaseModel):
    data: TransferCompletedData
    id: int = Field(..., description="Event ID")
    inserted_at: datetime = Field(..., description="Event timestamp")
    type: Literal["transfer.completed"] = Field(..., description="Event type")


class Requester(BaseModel):
    id: int | None = Field(None, description="Requester user ID")
    username: str | None = Field(None, description="Requester username")


class Responder(BaseModel):
    id: int | None = Field(None, description="Responder user ID")
    username: str | None = Field(None, description="Responder username")


class Request(BaseModel):
    amount: int = Field(..., description="Requested amount")
    id: int = Field(..., description="Request ID")
    label: str | None = Field(None, description="Request label")
    requested_at: datetime = Field(..., description="Request timestamp")
    requester: Requester
    resolved_at: datetime | None = Field(None, description="Resolution timestamp")
    responder: Responder
    status: str = Field(..., description="Request status")
    transaction_id: int | None = Field(None, description="Associated transaction ID")


class Pagination(BaseModel):
    limit: int | None = Field(None, description="Items per page")
    page: int | None = Field(None, description="Current page")
    total: int | None = Field(None, description="Total items")
    total_pages: int | None = Field(None, description="Total pages")


class RequestAcceptedData(BaseModel):
    amount: int = Field(..., description="Request amount")
    request_id: int = Field(..., description="Request ID")
    status: str = Field(..., description="New request status")
    transaction_id: int = Field(..., description="Created transaction ID")


class Type1(StrEnum):
    request_accepted = "request.accepted"


class RequestAcceptedEvent(BaseModel):
    data: RequestAcceptedData
    id: int = Field(..., description="Event ID")
    inserted_at: datetime = Field(..., description="Event timestamp")
    type: Literal["request.accepted"] = Field(..., description="Event type")


class PreauthApprovedData(BaseModel):
    bot_user_id: int = Field(..., description="Bot user ID")
    preauth_id: int = Field(..., description="Preauthorization ID")
    user_id: int = Field(..., description="Target user ID")


class Type2(StrEnum):
    preauth_revoked = "preauth.revoked"


class TransactionsResponse(BaseModel):
    pagination: Pagination | None = None
    transactions: list[Transaction] | None = Field(None, description="The transactions list")


class Type3(StrEnum):
    request_denied = "request.denied"


class RequestDeniedEvent(BaseModel):
    data: RequestDeniedData
    id: int = Field(..., description="Event ID")
    inserted_at: datetime = Field(..., description="Event timestamp")
    type: Literal["request.denied"] = Field(..., description="Event type")


class SendStkParams(BaseModel):
    amount: int = Field(..., description="Amount of STK to send")
    label: str | None = Field(None, description="Optional transaction label")


class RequestResponse(BaseModel):
    amount: int = Field(..., description="Requested amount")
    id: int = Field(..., description="Request ID")
    label: str | None = Field(None, description="Request label")
    requested_at: datetime = Field(..., description="Request timestamp")
    requester: Requester
    resolved_at: datetime | None = Field(None, description="Resolution timestamp")
    responder: Responder
    status: str = Field(..., description="Request status")
    transaction_id: int | None = Field(None, description="Associated transaction ID")


class RequestsResponse(BaseModel):
    pagination: Pagination | None = None
    requests: list[Request] | None = Field(None, description="The requests list")


class PreauthCreatedData(BaseModel):
    bot_user_id: int = Field(..., description="Bot user ID")
    max_amount: int = Field(..., description="Max amount per window")
    preauth_id: int = Field(..., description="Preauthorization ID")
    user_id: int = Field(..., description="Target user ID")
    window_hours: int = Field(..., description="Rolling window in hours")


class Type4(StrEnum):
    preauth_approved = "preauth.approved"


class PreauthApprovedEvent(BaseModel):
    data: PreauthApprovedData
    id: int = Field(..., description="Event ID")
    inserted_at: datetime = Field(..., description="Event timestamp")
    type: Literal["preauth.approved"] = Field(..., description="Event type")


class DiscordBotResponse(BaseModel):
    discord_id: str = Field(..., description="The Discord snowflake ID of the StackCoin bot")


class DiscordGuild(BaseModel):
    designated_channel_snowflake: str | None = Field(
        None, description="Designated channel snowflake ID"
    )
    id: int = Field(..., description="Guild ID")
    last_updated: datetime = Field(..., description="Last updated timestamp")
    name: str = Field(..., description="Guild name")
    snowflake: str = Field(..., description="Discord guild snowflake ID")


class PreauthRevokedData(BaseModel):
    bot_user_id: int = Field(..., description="Bot user ID")
    preauth_id: int = Field(..., description="Preauthorization ID")
    user_id: int = Field(..., description="Target user ID")


class DiscordGuildResponse(BaseModel):
    designated_channel_snowflake: str | None = Field(
        None, description="Designated channel snowflake ID"
    )
    id: int = Field(..., description="Guild ID")
    last_updated: datetime = Field(..., description="Last updated timestamp")
    name: str = Field(..., description="Guild name")
    snowflake: str = Field(..., description="Discord guild snowflake ID")


class SendStkResponse(BaseModel):
    amount: int = Field(..., description="Amount sent")
    from_new_balance: int = Field(..., description="Sender's new balance")
    success: bool = Field(..., description="Whether the operation succeeded")
    to_new_balance: int = Field(..., description="Recipient's new balance")
    transaction_id: int = Field(..., description="Created transaction ID")


class RequestCreatedData(BaseModel):
    amount: int = Field(..., description="Requested amount")
    label: str | None = Field(None, description="Request label")
    request_id: int = Field(..., description="Request ID")
    requester_id: int = Field(..., description="Requester user ID")
    responder_id: int = Field(..., description="Responder user ID")


class CreateRequestParams(BaseModel):
    amount: int = Field(..., description="Amount of STK to request")
    label: str | None = Field(None, description="Optional request label")


class Type5(StrEnum):
    request_created = "request.created"


class RequestCreatedEvent(BaseModel):
    data: RequestCreatedData
    id: int = Field(..., description="Event ID")
    inserted_at: datetime = Field(..., description="Event timestamp")
    type: Literal["request.created"] = Field(..., description="Event type")


class ErrorResponse(BaseModel):
    error: str = Field(..., description="Error message")


class UserResponse(BaseModel):
    admin: bool = Field(..., description="Whether user is an admin")
    balance: int = Field(..., description="User's STK balance")
    banned: bool = Field(..., description="Whether user is banned")
    id: int | None = Field(None, description="User ID")
    inserted_at: datetime | None = Field(None, description="Creation timestamp")
    updated_at: datetime | None = Field(None, description="Update timestamp")
    username: str = Field(..., description="Username")


class UsersResponse(BaseModel):
    pagination: Pagination | None = None
    users: list[User] | None = Field(None, description="The users list")


class CreateRequestResponse(BaseModel):
    amount: int = Field(..., description="Requested amount")
    request_id: int = Field(..., description="Created request ID")
    requested_at: datetime = Field(..., description="Request timestamp")
    requester: Requester
    responder: Responder
    status: str = Field(..., description="Request status")
    success: bool = Field(..., description="Whether the operation succeeded")
    transaction_id: int | None = Field(
        None, description="Transaction ID (present when preauth auto-confirmed)"
    )


class RequestActionResponse(BaseModel):
    request_id: int = Field(..., description="Request ID")
    resolved_at: datetime = Field(..., description="Resolution timestamp")
    status: str = Field(..., description="New request status")
    success: bool = Field(..., description="Whether the operation succeeded")
    transaction_id: int | None = Field(None, description="Associated transaction ID")


class Type6(StrEnum):
    preauth_created = "preauth.created"


class PreauthCreatedEvent(BaseModel):
    data: PreauthCreatedData
    id: int = Field(..., description="Event ID")
    inserted_at: datetime = Field(..., description="Event timestamp")
    type: Literal["preauth.created"] = Field(..., description="Event type")


class DiscordGuildsResponse(BaseModel):
    guilds: list[DiscordGuild] | None = Field(None, description="The guilds list")
    pagination: Pagination | None = None


class PreauthRevokedEvent(BaseModel):
    data: PreauthRevokedData
    id: int = Field(..., description="Event ID")
    inserted_at: datetime = Field(..., description="Event timestamp")
    type: Literal["preauth.revoked"] = Field(..., description="Event type")


class Event(
    RootModel[
        TransferCompletedEvent
        | RequestCreatedEvent
        | RequestAcceptedEvent
        | RequestDeniedEvent
        | PreauthCreatedEvent
        | PreauthApprovedEvent
        | PreauthRevokedEvent
    ]
):
    root: (
        TransferCompletedEvent
        | RequestCreatedEvent
        | RequestAcceptedEvent
        | RequestDeniedEvent
        | PreauthCreatedEvent
        | PreauthApprovedEvent
        | PreauthRevokedEvent
    ) = Field(
        ...,
        description="A StackCoin event (discriminated by type)",
        discriminator="type",
        title="Event",
    )


class EventsResponse(BaseModel):
    events: list[Event] = Field(..., description="The events list")
    has_more: bool = Field(..., description="Whether more events exist beyond this page")
